# Generated by Django 3.2.7 on 2022-08-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='password',
            new_name='Password',
        ),
    ]
